name: learn_hive
description: learn_hive

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: any
  hive: any
  hive_flutter: any
  get_it: any
  flutter_bloc: any
  equatable: any
  dartz: any
  connectivity: any
  http: any
  shared_preferences: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: any
  build_runner: any
  http: any
  google_fonts: any
  mockito: any

flutter:

  uses-material-design: true

